# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Chitrak's webpage

# Short description (goes below the title; it will also be used in the RSS feed)
description: This is the webpage of Chitrak Gupta.

# Your name, as you want it to appear underneath each post and in the footer
author: Chitrak Gupta

# Your email if you want it to be linked on the contact page
author_email: chitrakgupta144@gmail.com

# The directory for category index pages. Change it to something else if

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
#url: http://yourdomain.com/

gems: -jekyll-seo-tag
